version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: amanmemilih
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
