name: Continuous Integration
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/amanmemilih:${{ github.ref_name }}